### PR TITLE
added maxAge option

### PR DESCRIPTION
**Pull request by fmmsilva**

### CODE REVIEW

**Comment by moritzsternemann** [comment]
a test for this would be nice @fmmsilva

**Comment by fmmsilva** [comment]
done ;)

**Comment by am11** [comment]
Thanks for adding this new option @fmmsilva!
LGTM for most part, please:

* squash it down to two commits: one for feature addition and then for a test case.
* revert all the whitespace changes in test file. The existing format is intentional.

**Comment by fmmsilva** [comment]
Sorry, I'm new to git and I don't know how to squash it down to two commits, can you help me?

**Comment by fmmsilva** [comment]
Created new PR #69

**Pull request closed without merging**
