### PR TITLE
:bug: Add support for Node 0.12 and node-sass 2.0. Fixes #23

### LINKED ISSUE #23: Update to support node-sass ^2.0.0 and Node 0.12
I have forked the project and am trying to get tests to run after upgrading the package requirements to node-sass ^2.0.0, since this module will not install under Node 0.12.

Of course, I can't seem to get it to work or I would just submit a PR. Maybe you can figure out what's up?

### PR DESCRIPTION
**Pull request by jerone**
This PR adds support for Node 0.12 and node-sass 2.0.1.

Tests: :white_check_mark:

Fixes: https://github.com/sass/node-sass-middleware/issues/23

Ref: https://github.com/sass/node-sass/issues/656

PR-ready: :shipit:

### CODE REVIEW

**Comment by am11** [comment]
Thank you! :+1: :zap: 

Could you please also change .travis.yml to use 0.12 [here](https://github.com/sass/node-sass-middleware/blob/b8b6032fe5522ad95eff556f87e4d3e2da0563d0/.travis.yml#L4) (overwriting 0.11) in a separate commit? 0.11 was unstable branch which is superseded by node.js v0.12.

**Comment by jerone** [comment]
@am11 commented on [14 feb. 2015 22:52 CET](https://github.com/sass/node-sass-middleware/pull/24#issuecomment-74393507 "2015-02-14T21:52:36Z - Replied by Github Comment Enhancer"):
> Thank you!  :zap: 
> 
> Could you please also change .travis.yml to use 0.12 [here](https://github.com/sass/node-sass-middleware/blob/b8b6032fe5522ad95eff556f87e4d3e2da0563d0/.travis.yml#L4) (overwriting 0.11) in a separate commit? 0.11 was unstable branch which is superseded by node.js v0.12.

Just noticed that `node-sass` used version 0.10 & 0.12 and pushed a new commit same time as you commented :smile:

**Comment by am11** [comment]
Wow coincidence!! :smile: 

Thanks! :tada:

**Comment by jerone** [comment]
@am11 commented on [14 feb. 2015 23:00 CET](https://github.com/sass/node-sass-middleware/pull/24#issuecomment-74393764 "2015-02-14T22:00:03Z - Replied by Github Comment Enhancer"):
> Wow coincidence!! :smile: 
> 
> Thanks! :tada:

Great minds think alike :)
Thank for merging :fireworks:

**Pull request merged**
