### PR TITLE
Update node-sass version

### PR DESCRIPTION
**Pull request by clement-escolano**

### CODE REVIEW

**Comment by clement-escolano** [comment]
@am11 Is it possible to merge this one ?
It will update `node-sass` to the latest version.

**Comment by nschonni** [comment]
We don't use a lock file, so with the `^` version range, if you delete your node_modules and reinstall, it will already install 4.9.0

**Comment by clement-escolano** [comment]
@nschonni Indeed thanks ! Simply upgrading was not working but removing everything worked 😄

**Comment by am11** [comment]
Yup, we essentially need to do: `npm uninstall node-sass-middleware && npm install node-sass-middleware` to get latest minor version of node-sass.
In a separate PR, while improving/fixing the failing tests, I have updated all dependencies to latest stable version: https://github.com/sass/node-sass-middleware/pull/114.

**Pull request closed without merging**
