### PR TITLE
Created specific documentation on readme

### PR DESCRIPTION
**Pull request by Vercryger**
I had some issues with this module because there wasn't proper documentation, so i thought this improvement would be great!

### CODE REVIEW

**Comment by iMoritz** [comment]
nice! But you forgot sourceMaps ;)

**Comment by Vercryger** [comment]
Oh I knew there was something i was forgetting :(

**Comment by iMoritz** [comment]
:+1:

**Comment by am11** [comment]
Thanks. The changes look reasonable. :+1: 

Can you please squash the commits? Given the nature of this change-set, I'd squash all 13 to one commit.

**Comment by Vercryger** [comment]
You are welcome! Sure, no problem ;)

**Comment by am11** [comment]
@Vercryger, unfortunately the squashing is bit trickier. The end result being to have one commit instead of ~15 commits for this docs change. 

At this point, the easiest way would be to close this pull request, take the backup of your updated middleware.js and README.md, re-fork the repository and send a new pull request with a single commit. 

The git-way is to do the interactive rebasing, but it would probably be the bit challenging now, since you have a recursive merge commit (499955c). 

But I'd recommend to opt for the easier solution for the docs changes! :smile: 

Let me know if anything is unclear.

Thanks again for your contribution.

**Comment by Vercryger** [comment]
I think that would be a better idea, i will back up my changes and re-fork and send a new pull request ASAP :+1:

**Comment by am11** [comment]
Thanks.

**Pull request closed without merging**
